name: Pipeline de CI - Meu Primeiro Robô

on:
  push:
    branches: [ "main" ]

jobs:
  verificacoes-basicas:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Executar aplicação
        run: node app.js

      - name: Mensagem de sucesso
        run: echo "✅ Tudo funcionando corretamente!"
